global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'services'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
