CREATE USER svc_a WITH PASSWORD 'dev';
CREATE USER svc_b WITH PASSWORD 'dev';
CREATE USER svc_c WITH PASSWORD 'dev';
CREATE USER svc_d WITH PASSWORD 'dev';

CREATE DATABASE svc_a_db OWNER svc_a;
CREATE DATABASE svc_b_db OWNER svc_b;
CREATE DATABASE svc_c_db OWNER svc_c;
CREATE DATABASE svc_d_db OWNER svc_d;

GRANT ALL PRIVILEGES ON DATABASE svc_a_db TO svc_a;
GRANT ALL PRIVILEGES ON DATABASE svc_b_db TO svc_b;
GRANT ALL PRIVILEGES ON DATABASE svc_c_db TO svc_c;
GRANT ALL PRIVILEGES ON DATABASE svc_d_db TO svc_d;
